version: '3.3'

services:
  php:
    build: docker/
    links:
      - db:mysqldb
    volumes:
      - .:/var/www/html/
      - ./../docker/config-php/xdebug.ini:/user/local/etc/php/conf.d/xdebug.ini
    ports:
      - 81:80
  db:
    image: mysql
    volumes:
      - db_data:/varlib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
volumes:
  db_data: