<?php

namespace OC\PlatformBundle\Repository;

use http\Exception\InvalidArgumentException;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationWithAdvert($limit)
    {
        if($limit === null){
           throw new InvalidArgumentException("please specify max result of your query");
        }

        $qb = $this->createQueryBuilder('a');

        $qb->innerJoin('a.advert','adv')->addSelect('adv');
        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
